### ISSUE TITLE
Get lokasi user agar data yang tampil di home adalah provinsi user

### ISSUE THREAD

**Issue by fiqryq** [fiqryq/Pantaucovid#9]

**Comment by rootdavinalfa** [comment]
@fiqryq Ga bisa assign sendiri / ganti label karena bukan direct contributor

**Comment by fiqryq** [comment]
@rootdavinalfa  cek email vin

**Comment by amirisback** [comment]
I/System.out: ADRESS: []
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sunflower.pantaucovid19, PID: 16566
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sunflower.pantaucovid19/com.sunflower.pantaucovid19.MainActivity}: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:411)
        at com.sunflower.pantaucovid19.utils.Geography.getLocationObject(Geography.kt:43)
        at com.sunflower.pantaucovid19.MainActivity.onCreate(MainActivity.java:26)
        at android.app.Activity.performCreate(Activity.java:6662)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
I/Process: Sending signal. PID: 16566 SIG: 9


@rootdavinalfa

**Comment by amirisback** [comment]
@rootdavinalfa 
Error ga ngeget data, ga ada error handling jadinya force close

**Comment by amirisback** [comment]
Tapi testingnya dari emulator, belum di device asli

**Comment by rootdavinalfa** [comment]
Device asli ga ada masalah.Entar tak bikinin error handling nya

**Comment by amirisback** [comment]
siap, lanjutkan
